### ISSUE TITLE
Admin build fails

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/landing-page#105]
During `npm run build` I get:
```
> research-software-directory-admin@2.0.0 build /home/stefanv/git/rsd/admin
> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.8.3 and /home/stefanv/git/rsd/admin/tsconfig.json
/home/stefanv/git/rsd/admin/node_modules/webpack/lib/Chunk.js:533
		throw new Error("Chunk.entrypoints: Use Chunks.addGroup instead");
		^

Error: Chunk.entrypoints: Use Chunks.addGroup instead
    at Chunk.set (/home/stefanv/git/rsd/admin/node_modules/webpack/lib/Chunk.js:533:9)
    at /home/stefanv/git/rsd/admin/node_modules/extract-text-webpack-plugin/dist/index.js:176:40
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (/home/stefanv/git/rsd/admin/node_modules/extract-text-webpack-plugin/dist/index.js:171:18)
    at Compilation.applyPluginsAsyncSeries (/home/stefanv/git/rsd/admin/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/home/stefanv/git/rsd/admin/node_modules/react-scripts-ts/node_modules/webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/home/stefanv/git/rsd/admin/node_modules/react-scripts-ts/node_modules/webpack/lib/Compiler.js:508:17)
    at /home/stefanv/git/rsd/admin/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/stefanv/git/rsd/admin/node_modules/react-scripts-ts/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/stefanv/git/rsd/admin/node_modules/react-scripts-ts/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

The node_modules dir was removed and `npm install` was run before the build command.

**Comment by sverhoeven** [comment]
The builds on Travis-CI succeed, but they use yarn.

**Comment by sverhoeven** [comment]
When I try to use yarn I also get a successful build.

The documentation should be updated to use yarn or fix the npm build error.
